// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deadLetteredSince = `-- name: DeadLetteredSince :many
SELECT DISTINCT d.destination_id, dest.name
FROM deliveries d
JOIN destinations dest ON dest.id = d.destination_id
WHERE d.status = 'dead_lettered' AND d.dead_lettered_at >= $1
`

type DeadLetteredSinceRow struct {
	DestinationID pgtype.UUID `json:"destination_id"`
	Name          string      `json:"name"`
}

// Destinations that had at least one delivery dead-letter within the window,
// for the DLQ alert condition (BR-19).
func (q *Queries) DeadLetteredSince(ctx context.Context, deadLetteredAt pgtype.Timestamptz) ([]DeadLetteredSinceRow, error) {
	rows, err := q.db.Query(ctx, deadLetteredSince, deadLetteredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeadLetteredSinceRow
	for rows.Next() {
		var i DeadLetteredSinceRow
		if err := rows.Scan(&i.DestinationID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deliveryFailureRatesSince = `-- name: DeliveryFailureRatesSince :many
SELECT d.destination_id, dest.name,
       count(*) AS total,
       count(*) FILTER (WHERE d.status = 'dead_lettered') AS failures
FROM deliveries d
JOIN destinations dest ON dest.id = d.destination_id
WHERE d.status IN ('succeeded', 'dead_lettered') AND d.updated_at >= $1
GROUP BY d.destination_id, dest.name
`

type DeliveryFailureRatesSinceRow struct {
	DestinationID pgtype.UUID `json:"destination_id"`
	Name          string      `json:"name"`
	Total         int64       `json:"total"`
	Failures      int64       `json:"failures"`
}

// Per-destination terminal delivery counts within the window, for the
// failure-rate condition. Only terminal outcomes count toward the rate; a
// delivery still retrying ('failed'/'pending') is not yet a success or a loss.
func (q *Queries) DeliveryFailureRatesSince(ctx context.Context, updatedAt pgtype.Timestamptz) ([]DeliveryFailureRatesSinceRow, error) {
	rows, err := q.db.Query(ctx, deliveryFailureRatesSince, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryFailureRatesSinceRow
	for rows.Next() {
		var i DeliveryFailureRatesSinceRow
		if err := rows.Scan(
			&i.DestinationID,
			&i.Name,
			&i.Total,
			&i.Failures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlertLastFired = `-- name: GetAlertLastFired :one
SELECT last_fired_at FROM alert_state
WHERE destination_id = $1 AND condition = $2
`

type GetAlertLastFiredParams struct {
	DestinationID pgtype.UUID `json:"destination_id"`
	Condition     string      `json:"condition"`
}

func (q *Queries) GetAlertLastFired(ctx context.Context, arg GetAlertLastFiredParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getAlertLastFired, arg.DestinationID, arg.Condition)
	var last_fired_at pgtype.Timestamptz
	err := row.Scan(&last_fired_at)
	return last_fired_at, err
}

const markAlertFired = `-- name: MarkAlertFired :exec
INSERT INTO alert_state (destination_id, condition, last_fired_at)
VALUES ($1, $2, $3)
ON CONFLICT (destination_id, condition) DO UPDATE SET last_fired_at = $3
`

type MarkAlertFiredParams struct {
	DestinationID pgtype.UUID        `json:"destination_id"`
	Condition     string             `json:"condition"`
	LastFiredAt   pgtype.Timestamptz `json:"last_fired_at"`
}

func (q *Queries) MarkAlertFired(ctx context.Context, arg MarkAlertFiredParams) error {
	_, err := q.db.Exec(ctx, markAlertFired, arg.DestinationID, arg.Condition, arg.LastFiredAt)
	return err
}
