// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dedup.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDedupeKey = `-- name: ClaimDedupeKey :one
INSERT INTO dedup_index (source_id, dedupe_key, event_id, expires_at)
VALUES (
    $1, $2, $3,
    now() + ($4::int * interval '1 second')
)
ON CONFLICT (source_id, dedupe_key) DO UPDATE
    SET event_id  = EXCLUDED.event_id,
        expires_at = EXCLUDED.expires_at
    WHERE dedup_index.expires_at <= now()
RETURNING event_id
`

type ClaimDedupeKeyParams struct {
	SourceID      pgtype.UUID `json:"source_id"`
	DedupeKey     string      `json:"dedupe_key"`
	EventID       pgtype.UUID `json:"event_id"`
	WindowSeconds int32       `json:"window_seconds"`
}

// Claims a dedupe key for an event, returning the claiming event id.
func (q *Queries) ClaimDedupeKey(ctx context.Context, arg ClaimDedupeKeyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimDedupeKey,
		arg.SourceID,
		arg.DedupeKey,
		arg.EventID,
		arg.WindowSeconds,
	)
	var event_id pgtype.UUID
	err := row.Scan(&event_id)
	return event_id, err
}

const deleteExpiredDedupEntries = `-- name: DeleteExpiredDedupEntries :execrows
DELETE FROM dedup_index WHERE expires_at <= now()
`

// Housekeeping for keys past their window, run periodically. ClaimDedupeKey
// already reclaims expired rows in place, so this only keeps the table from
// growing one row per unique key forever.
func (q *Queries) DeleteExpiredDedupEntries(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredDedupEntries)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
