// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertDelivery = `-- name: InsertDelivery :one
INSERT INTO deliveries (
    tenant_id,
    event_id,
    destination_id
) VALUES (
    $1, $2, $3
)
RETURNING id
`

type InsertDeliveryParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	EventID       pgtype.UUID `json:"event_id"`
	DestinationID pgtype.UUID `json:"destination_id"`
}

// Creates the pending delivery for an (event, destination) pair produced by
// fan-out at ingest. status defaults to 'pending' and attempt_count to 0; the
// River job that drives it is enqueued in the same transaction and its id
// backfilled via SetDeliveryRiverJobID.
func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertDelivery, arg.TenantID, arg.EventID, arg.DestinationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const setDeliveryRiverJobID = `-- name: SetDeliveryRiverJobID :exec
UPDATE deliveries
SET river_job_id = $2
WHERE id = $1
`

type SetDeliveryRiverJobIDParams struct {
	ID         pgtype.UUID `json:"id"`
	RiverJobID pgtype.Int8 `json:"river_job_id"`
}

// Backfills the River job id onto a delivery once the job is enqueued, so the
// queue row can be cross-referenced from the delivery while debugging (BR-17).
func (q *Queries) SetDeliveryRiverJobID(ctx context.Context, arg SetDeliveryRiverJobIDParams) error {
	_, err := q.db.Exec(ctx, setDeliveryRiverJobID, arg.ID, arg.RiverJobID)
	return err
}
