// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDelivery = `-- name: GetDelivery :one
SELECT id, tenant_id, event_id, destination_id, river_job_id, status, attempt_count, next_attempt_at, last_attempted_at, dead_lettered_at, created_at, updated_at FROM deliveries
WHERE id = $1
`

func (q *Queries) GetDelivery(ctx context.Context, id pgtype.UUID) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventID,
		&i.DestinationID,
		&i.RiverJobID,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastAttemptedAt,
		&i.DeadLetteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :one
INSERT INTO deliveries (
    tenant_id,
    event_id,
    destination_id
) VALUES (
    $1, $2, $3
)
RETURNING id
`

type InsertDeliveryParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	EventID       pgtype.UUID `json:"event_id"`
	DestinationID pgtype.UUID `json:"destination_id"`
}

// Creates the pending delivery for an (event, destination) pair produced by
// fan-out at ingest. status defaults to 'pending' and attempt_count to 0; the
// River job that drives it is enqueued in the same transaction and its id
// backfilled via SetDeliveryRiverJobID.
func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertDelivery, arg.TenantID, arg.EventID, arg.DestinationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const setDeliveryRiverJobID = `-- name: SetDeliveryRiverJobID :exec
UPDATE deliveries
SET river_job_id = $2
WHERE id = $1
`

type SetDeliveryRiverJobIDParams struct {
	ID         pgtype.UUID `json:"id"`
	RiverJobID pgtype.Int8 `json:"river_job_id"`
}

// Backfills the River job id onto a delivery once the job is enqueued, so the
// queue row can be cross-referenced from the delivery while debugging (BR-17).
func (q *Queries) SetDeliveryRiverJobID(ctx context.Context, arg SetDeliveryRiverJobIDParams) error {
	_, err := q.db.Exec(ctx, setDeliveryRiverJobID, arg.ID, arg.RiverJobID)
	return err
}

const updateDeliveryOutcome = `-- name: UpdateDeliveryOutcome :exec
UPDATE deliveries
SET status = $2,
    attempt_count = $3,
    last_attempted_at = now(),
    updated_at = now()
WHERE id = $1
`

type UpdateDeliveryOutcomeParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	AttemptCount int32       `json:"attempt_count"`
}

func (q *Queries) UpdateDeliveryOutcome(ctx context.Context, arg UpdateDeliveryOutcomeParams) error {
	_, err := q.db.Exec(ctx, updateDeliveryOutcome, arg.ID, arg.Status, arg.AttemptCount)
	return err
}
