// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDelivery = `-- name: GetDelivery :one
SELECT id, tenant_id, event_id, destination_id, river_job_id, status, attempt_count, next_attempt_at, last_attempted_at, dead_lettered_at, created_at, updated_at FROM deliveries
WHERE id = $1
`

func (q *Queries) GetDelivery(ctx context.Context, id pgtype.UUID) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventID,
		&i.DestinationID,
		&i.RiverJobID,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastAttemptedAt,
		&i.DeadLetteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :one
INSERT INTO deliveries (
    tenant_id,
    event_id,
    destination_id
) VALUES (
    $1, $2, $3
)
RETURNING id
`

type InsertDeliveryParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	EventID       pgtype.UUID `json:"event_id"`
	DestinationID pgtype.UUID `json:"destination_id"`
}

// Creates the pending delivery for an (event, destination) pair produced by
// fan-out at ingest. status defaults to 'pending' and attempt_count to 0; the
// River job that drives it is enqueued in the same transaction and its id
// backfilled via SetDeliveryRiverJobID.
func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertDelivery, arg.TenantID, arg.EventID, arg.DestinationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const recordDeliveryOutcome = `-- name: RecordDeliveryOutcome :one
UPDATE deliveries
SET status = $2,
    attempt_count = attempt_count + 1,
    last_attempted_at = now(),
    dead_lettered_at = CASE WHEN $2 = 'dead_lettered' THEN now() ELSE dead_lettered_at END,
    updated_at = now()
WHERE id = $1
RETURNING attempt_count
`

type RecordDeliveryOutcomeParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Applies the result of one attempt. Returns the new attempt_count
// to number the delivery_attempts row.
func (q *Queries) RecordDeliveryOutcome(ctx context.Context, arg RecordDeliveryOutcomeParams) (int32, error) {
	row := q.db.QueryRow(ctx, recordDeliveryOutcome, arg.ID, arg.Status)
	var attempt_count int32
	err := row.Scan(&attempt_count)
	return attempt_count, err
}

const resetDeliveryForRecovery = `-- name: ResetDeliveryForRecovery :exec
UPDATE deliveries
SET status = 'pending',
    dead_lettered_at = NULL,
    next_attempt_at = NULL,
    updated_at = now()
WHERE id = $1
`

// Returns a dead-lettered delivery to the queue for a fresh set of attempts.
// attempt_count is intentionally left as-is so the
// attempt history stays continuous; the re-enqueued River job gets its own
// fresh retry budget.
func (q *Queries) ResetDeliveryForRecovery(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetDeliveryForRecovery, id)
	return err
}

const setDeliveryRiverJobID = `-- name: SetDeliveryRiverJobID :exec
UPDATE deliveries
SET river_job_id = $2
WHERE id = $1
`

type SetDeliveryRiverJobIDParams struct {
	ID         pgtype.UUID `json:"id"`
	RiverJobID pgtype.Int8 `json:"river_job_id"`
}

// Backfills the River job id onto a delivery once the job is enqueued, so the
// queue row can be cross-referenced from the delivery while debugging (BR-17).
func (q *Queries) SetDeliveryRiverJobID(ctx context.Context, arg SetDeliveryRiverJobIDParams) error {
	_, err := q.db.Exec(ctx, setDeliveryRiverJobID, arg.ID, arg.RiverJobID)
	return err
}
