// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertDeliveryAttempt = `-- name: InsertDeliveryAttempt :exec
INSERT INTO delivery_attempts (
    delivery_id,
    attempt_number,
    request_headers,
    response_status_code,
    response_headers,
    response_body_truncated,
    error,
    duration_ms
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertDeliveryAttemptParams struct {
	DeliveryID            pgtype.UUID `json:"delivery_id"`
	AttemptNumber         int32       `json:"attempt_number"`
	RequestHeaders        []byte      `json:"request_headers"`
	ResponseStatusCode    pgtype.Int4 `json:"response_status_code"`
	ResponseHeaders       []byte      `json:"response_headers"`
	ResponseBodyTruncated pgtype.Text `json:"response_body_truncated"`
	Error                 pgtype.Text `json:"error"`
	DurationMs            pgtype.Int4 `json:"duration_ms"`
}

// Records one HTTP try against a destination for the trace view.
func (q *Queries) InsertDeliveryAttempt(ctx context.Context, arg InsertDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, insertDeliveryAttempt,
		arg.DeliveryID,
		arg.AttemptNumber,
		arg.RequestHeaders,
		arg.ResponseStatusCode,
		arg.ResponseHeaders,
		arg.ResponseBodyTruncated,
		arg.Error,
		arg.DurationMs,
	)
	return err
}
