// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: destinations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDestination = `-- name: DeleteDestination :execrows
DELETE FROM destinations
WHERE id = $1 AND tenant_id = $2
`

type DeleteDestinationParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteDestination(ctx context.Context, arg DeleteDestinationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDestination, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDestination = `-- name: GetDestination :one
SELECT id, tenant_id, name, url, auth_config, timeout_ms, rate_limit_per_second, max_attempts, backoff_base_seconds, backoff_max_seconds, paused_at, created_at, updated_at FROM destinations
WHERE id = $1 AND tenant_id = $2
`

type GetDestinationParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetDestination(ctx context.Context, arg GetDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, getDestination, arg.ID, arg.TenantID)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.AuthConfig,
		&i.TimeoutMs,
		&i.RateLimitPerSecond,
		&i.MaxAttempts,
		&i.BackoffBaseSeconds,
		&i.BackoffMaxSeconds,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDestination = `-- name: InsertDestination :one
INSERT INTO destinations (
    tenant_id,
    name,
    url,
    auth_config,
    timeout_ms,
    rate_limit_per_second,
    max_attempts,
    backoff_base_seconds,
    backoff_max_seconds
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, tenant_id, name, url, auth_config, timeout_ms, rate_limit_per_second, max_attempts, backoff_base_seconds, backoff_max_seconds, paused_at, created_at, updated_at
`

type InsertDestinationParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	Name               string      `json:"name"`
	Url                string      `json:"url"`
	AuthConfig         []byte      `json:"auth_config"`
	TimeoutMs          int32       `json:"timeout_ms"`
	RateLimitPerSecond pgtype.Int4 `json:"rate_limit_per_second"`
	MaxAttempts        int32       `json:"max_attempts"`
	BackoffBaseSeconds int32       `json:"backoff_base_seconds"`
	BackoffMaxSeconds  int32       `json:"backoff_max_seconds"`
}

func (q *Queries) InsertDestination(ctx context.Context, arg InsertDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, insertDestination,
		arg.TenantID,
		arg.Name,
		arg.Url,
		arg.AuthConfig,
		arg.TimeoutMs,
		arg.RateLimitPerSecond,
		arg.MaxAttempts,
		arg.BackoffBaseSeconds,
		arg.BackoffMaxSeconds,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.AuthConfig,
		&i.TimeoutMs,
		&i.RateLimitPerSecond,
		&i.MaxAttempts,
		&i.BackoffBaseSeconds,
		&i.BackoffMaxSeconds,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDestinations = `-- name: ListDestinations :many
SELECT id, tenant_id, name, url, auth_config, timeout_ms, rate_limit_per_second, max_attempts, backoff_base_seconds, backoff_max_seconds, paused_at, created_at, updated_at FROM destinations
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDestinations(ctx context.Context, tenantID pgtype.UUID) ([]Destination, error) {
	rows, err := q.db.Query(ctx, listDestinations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Destination
	for rows.Next() {
		var i Destination
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Url,
			&i.AuthConfig,
			&i.TimeoutMs,
			&i.RateLimitPerSecond,
			&i.MaxAttempts,
			&i.BackoffBaseSeconds,
			&i.BackoffMaxSeconds,
			&i.PausedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseDestination = `-- name: PauseDestination :one
UPDATE destinations
SET paused_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, url, auth_config, timeout_ms, rate_limit_per_second, max_attempts, backoff_base_seconds, backoff_max_seconds, paused_at, created_at, updated_at
`

type PauseDestinationParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) PauseDestination(ctx context.Context, arg PauseDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, pauseDestination, arg.ID, arg.TenantID)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.AuthConfig,
		&i.TimeoutMs,
		&i.RateLimitPerSecond,
		&i.MaxAttempts,
		&i.BackoffBaseSeconds,
		&i.BackoffMaxSeconds,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resumeDestination = `-- name: ResumeDestination :one
UPDATE destinations
SET paused_at = NULL
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, url, auth_config, timeout_ms, rate_limit_per_second, max_attempts, backoff_base_seconds, backoff_max_seconds, paused_at, created_at, updated_at
`

type ResumeDestinationParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ResumeDestination(ctx context.Context, arg ResumeDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, resumeDestination, arg.ID, arg.TenantID)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.AuthConfig,
		&i.TimeoutMs,
		&i.RateLimitPerSecond,
		&i.MaxAttempts,
		&i.BackoffBaseSeconds,
		&i.BackoffMaxSeconds,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDestination = `-- name: UpdateDestination :one
UPDATE destinations
SET
    name = $3,
    url = $4,
    auth_config = $5,
    timeout_ms = $6,
    rate_limit_per_second = $7,
    max_attempts = $8,
    backoff_base_seconds = $9,
    backoff_max_seconds = $10,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, url, auth_config, timeout_ms, rate_limit_per_second, max_attempts, backoff_base_seconds, backoff_max_seconds, paused_at, created_at, updated_at
`

type UpdateDestinationParams struct {
	ID                 pgtype.UUID `json:"id"`
	TenantID           pgtype.UUID `json:"tenant_id"`
	Name               string      `json:"name"`
	Url                string      `json:"url"`
	AuthConfig         []byte      `json:"auth_config"`
	TimeoutMs          int32       `json:"timeout_ms"`
	RateLimitPerSecond pgtype.Int4 `json:"rate_limit_per_second"`
	MaxAttempts        int32       `json:"max_attempts"`
	BackoffBaseSeconds int32       `json:"backoff_base_seconds"`
	BackoffMaxSeconds  int32       `json:"backoff_max_seconds"`
}

func (q *Queries) UpdateDestination(ctx context.Context, arg UpdateDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, updateDestination,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Url,
		arg.AuthConfig,
		arg.TimeoutMs,
		arg.RateLimitPerSecond,
		arg.MaxAttempts,
		arg.BackoffBaseSeconds,
		arg.BackoffMaxSeconds,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.AuthConfig,
		&i.TimeoutMs,
		&i.RateLimitPerSecond,
		&i.MaxAttempts,
		&i.BackoffBaseSeconds,
		&i.BackoffMaxSeconds,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
