// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventForDelivery = `-- name: GetEventForDelivery :one
SELECT raw_body, content_type FROM events
WHERE id = $1
`

type GetEventForDeliveryRow struct {
	RawBody     []byte      `json:"raw_body"`
	ContentType pgtype.Text `json:"content_type"`
}

// The bytes a delivery pushes to its destination: the verbatim payload and the
// content type to send it under. Provider headers are intentionally not
// forwarded (a delivery is a fresh request, not a proxy of the inbound one).
func (q *Queries) GetEventForDelivery(ctx context.Context, id pgtype.UUID) (GetEventForDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getEventForDelivery, id)
	var i GetEventForDeliveryRow
	err := row.Scan(&i.RawBody, &i.ContentType)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (
    tenant_id,
    source_id,
    raw_headers,
    raw_body,
    content_type,
    parsed_body,
    dedupe_key,
    verified
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, received_at
`

type InsertEventParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	SourceID    pgtype.UUID `json:"source_id"`
	RawHeaders  []byte      `json:"raw_headers"`
	RawBody     []byte      `json:"raw_body"`
	ContentType pgtype.Text `json:"content_type"`
	ParsedBody  []byte      `json:"parsed_body"`
	DedupeKey   pgtype.Text `json:"dedupe_key"`
	Verified    bool        `json:"verified"`
}

type InsertEventRow struct {
	ID         pgtype.UUID        `json:"id"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

// Persists an inbound webhook: raw_headers as JSONB,
// raw_body as the exact bytes received, parsed_body a best-effort JSON parse
// (NULL when unstructured), and verified the signature-check result.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (InsertEventRow, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.TenantID,
		arg.SourceID,
		arg.RawHeaders,
		arg.RawBody,
		arg.ContentType,
		arg.ParsedBody,
		arg.DedupeKey,
		arg.Verified,
	)
	var i InsertEventRow
	err := row.Scan(&i.ID, &i.ReceivedAt)
	return i, err
}
