// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_settings.sql

package db

import (
	"context"
)

const getInstanceSetting = `-- name: GetInstanceSetting :one
SELECT value FROM instance_settings WHERE key = $1
`

func (q *Queries) GetInstanceSetting(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getInstanceSetting, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const upsertInstanceSetting = `-- name: UpsertInstanceSetting :exec
INSERT INTO instance_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = now()
`

type UpsertInstanceSettingParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) UpsertInstanceSetting(ctx context.Context, arg UpsertInstanceSettingParams) error {
	_, err := q.db.Exec(ctx, upsertInstanceSetting, arg.Key, arg.Value)
	return err
}
