// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	Scopes     []string           `json:"scopes"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type DedupIndex struct {
	SourceID  pgtype.UUID        `json:"source_id"`
	DedupeKey string             `json:"dedupe_key"`
	EventID   pgtype.UUID        `json:"event_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Delivery struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	EventID         pgtype.UUID        `json:"event_id"`
	DestinationID   pgtype.UUID        `json:"destination_id"`
	RiverJobID      pgtype.Int8        `json:"river_job_id"`
	Status          string             `json:"status"`
	AttemptCount    int32              `json:"attempt_count"`
	NextAttemptAt   pgtype.Timestamptz `json:"next_attempt_at"`
	LastAttemptedAt pgtype.Timestamptz `json:"last_attempted_at"`
	DeadLetteredAt  pgtype.Timestamptz `json:"dead_lettered_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DeliveryAttempt struct {
	ID                    pgtype.UUID        `json:"id"`
	DeliveryID            pgtype.UUID        `json:"delivery_id"`
	AttemptNumber         int32              `json:"attempt_number"`
	RequestHeaders        []byte             `json:"request_headers"`
	ResponseStatusCode    pgtype.Int4        `json:"response_status_code"`
	ResponseHeaders       []byte             `json:"response_headers"`
	ResponseBodyTruncated pgtype.Text        `json:"response_body_truncated"`
	Error                 pgtype.Text        `json:"error"`
	DurationMs            pgtype.Int4        `json:"duration_ms"`
	AttemptedAt           pgtype.Timestamptz `json:"attempted_at"`
}

type Destination struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	Name               string             `json:"name"`
	Url                string             `json:"url"`
	AuthConfig         []byte             `json:"auth_config"`
	TimeoutMs          int32              `json:"timeout_ms"`
	RateLimitPerSecond pgtype.Int4        `json:"rate_limit_per_second"`
	MaxAttempts        int32              `json:"max_attempts"`
	BackoffBaseSeconds int32              `json:"backoff_base_seconds"`
	BackoffMaxSeconds  int32              `json:"backoff_max_seconds"`
	PausedAt           pgtype.Timestamptz `json:"paused_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	SourceID     pgtype.UUID        `json:"source_id"`
	RawHeaders   []byte             `json:"raw_headers"`
	RawBody      []byte             `json:"raw_body"`
	ContentType  pgtype.Text        `json:"content_type"`
	ParsedBody   []byte             `json:"parsed_body"`
	DedupeKey    pgtype.Text        `json:"dedupe_key"`
	Verified     bool               `json:"verified"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	SearchVector interface{}        `json:"search_vector"`
}

type InstanceSetting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Replay struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	RequestedBy   pgtype.UUID        `json:"requested_by"`
	Filter        []byte             `json:"filter"`
	Status        string             `json:"status"`
	MatchedCount  pgtype.Int4        `json:"matched_count"`
	RequeuedCount pgtype.Int4        `json:"requeued_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type Route struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	SourceID      pgtype.UUID        `json:"source_id"`
	DestinationID pgtype.UUID        `json:"destination_id"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Rule struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	SourceID            pgtype.UUID        `json:"source_id"`
	Name                string             `json:"name"`
	Expression          string             `json:"expression"`
	Action              string             `json:"action"`
	RouteDestinationIds []pgtype.UUID      `json:"route_destination_ids"`
	Priority            int32              `json:"priority"`
	Enabled             bool               `json:"enabled"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Source struct {
	ID                      pgtype.UUID        `json:"id"`
	TenantID                pgtype.UUID        `json:"tenant_id"`
	Name                    string             `json:"name"`
	ProviderType            string             `json:"provider_type"`
	EndpointPath            string             `json:"endpoint_path"`
	SigningSecretEncrypted  []byte             `json:"signing_secret_encrypted"`
	SigningSecretKeyVersion pgtype.Int4        `json:"signing_secret_key_version"`
	VerificationConfig      []byte             `json:"verification_config"`
	DedupeEnabled           bool               `json:"dedupe_enabled"`
	DedupeStrategy          pgtype.Text        `json:"dedupe_strategy"`
	DedupeFieldPath         pgtype.Text        `json:"dedupe_field_path"`
	DedupeWindowSeconds     int32              `json:"dedupe_window_seconds"`
	PausedAt                pgtype.Timestamptz `json:"paused_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Slug               string             `json:"slug"`
	Plan               string             `json:"plan"`
	EventsQuotaMonthly pgtype.Int8        `json:"events_quota_monthly"`
	RetentionDays      int32              `json:"retention_days"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	OidcSubject  pgtype.Text        `json:"oidc_subject"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
