// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replays.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishReplay = `-- name: FinishReplay :exec
UPDATE replays
SET status = $2,
    matched_count = $3,
    requeued_count = $4,
    completed_at = now()
WHERE id = $1
`

type FinishReplayParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        string      `json:"status"`
	MatchedCount  pgtype.Int4 `json:"matched_count"`
	RequeuedCount pgtype.Int4 `json:"requeued_count"`
}

// Records the terminal outcome of a bulk replay: 'completed' with the matched
// and requeued counts, or 'failed'.
func (q *Queries) FinishReplay(ctx context.Context, arg FinishReplayParams) error {
	_, err := q.db.Exec(ctx, finishReplay,
		arg.ID,
		arg.Status,
		arg.MatchedCount,
		arg.RequeuedCount,
	)
	return err
}

const getReplay = `-- name: GetReplay :one
SELECT id, tenant_id, requested_by, filter, status, matched_count, requeued_count, created_at, completed_at
FROM replays
WHERE id = $1
`

func (q *Queries) GetReplay(ctx context.Context, id pgtype.UUID) (Replay, error) {
	row := q.db.QueryRow(ctx, getReplay, id)
	var i Replay
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequestedBy,
		&i.Filter,
		&i.Status,
		&i.MatchedCount,
		&i.RequeuedCount,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertReplay = `-- name: InsertReplay :one
INSERT INTO replays (
    tenant_id,
    requested_by,
    filter
) VALUES (
    $1, $2, $3
)
RETURNING id, tenant_id, filter, status, matched_count, requeued_count, created_at, completed_at
`

type InsertReplayParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	RequestedBy pgtype.UUID `json:"requested_by"`
	Filter      []byte      `json:"filter"`
}

type InsertReplayRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Filter        []byte             `json:"filter"`
	Status        string             `json:"status"`
	MatchedCount  pgtype.Int4        `json:"matched_count"`
	RequeuedCount pgtype.Int4        `json:"requeued_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

// Opens a bulk-replay record
func (q *Queries) InsertReplay(ctx context.Context, arg InsertReplayParams) (InsertReplayRow, error) {
	row := q.db.QueryRow(ctx, insertReplay, arg.TenantID, arg.RequestedBy, arg.Filter)
	var i InsertReplayRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Filter,
		&i.Status,
		&i.MatchedCount,
		&i.RequeuedCount,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
