// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRoute = `-- name: DeleteRoute :execrows
DELETE FROM routes
WHERE id = $1 AND tenant_id = $2
`

type DeleteRouteParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteRoute(ctx context.Context, arg DeleteRouteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoute, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoute = `-- name: GetRoute :one
SELECT id, tenant_id, source_id, destination_id, enabled, created_at FROM routes
WHERE id = $1 AND tenant_id = $2
`

type GetRouteParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetRoute(ctx context.Context, arg GetRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, getRoute, arg.ID, arg.TenantID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceID,
		&i.DestinationID,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const insertRoute = `-- name: InsertRoute :one
INSERT INTO routes (
    tenant_id,
    source_id,
    destination_id,
    enabled
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, tenant_id, source_id, destination_id, enabled, created_at
`

type InsertRouteParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	SourceID      pgtype.UUID `json:"source_id"`
	DestinationID pgtype.UUID `json:"destination_id"`
	Enabled       bool        `json:"enabled"`
}

func (q *Queries) InsertRoute(ctx context.Context, arg InsertRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, insertRoute,
		arg.TenantID,
		arg.SourceID,
		arg.DestinationID,
		arg.Enabled,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceID,
		&i.DestinationID,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledDestinationIDsForSource = `-- name: ListEnabledDestinationIDsForSource :many
SELECT destination_id FROM routes
WHERE source_id = $1 AND enabled = true
`

// Destinations an event from this source fans out to: enabled routes only.
func (q *Queries) ListEnabledDestinationIDsForSource(ctx context.Context, sourceID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listEnabledDestinationIDsForSource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var destination_id pgtype.UUID
		if err := rows.Scan(&destination_id); err != nil {
			return nil, err
		}
		items = append(items, destination_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, tenant_id, source_id, destination_id, enabled, created_at FROM routes
WHERE tenant_id = $1
    AND ($2::uuid IS NULL OR source_id = $2)
    AND ($3::uuid IS NULL OR destination_id = $3)
ORDER BY created_at DESC
`

type ListRoutesParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	SourceID      pgtype.UUID `json:"source_id"`
	DestinationID pgtype.UUID `json:"destination_id"`
}

func (q *Queries) ListRoutes(ctx context.Context, arg ListRoutesParams) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutes, arg.TenantID, arg.SourceID, arg.DestinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceID,
			&i.DestinationID,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRouteEnabled = `-- name: UpdateRouteEnabled :one
UPDATE routes
SET enabled = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, source_id, destination_id, enabled, created_at
`

type UpdateRouteEnabledParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Enabled  bool        `json:"enabled"`
}

func (q *Queries) UpdateRouteEnabled(ctx context.Context, arg UpdateRouteEnabledParams) (Route, error) {
	row := q.db.QueryRow(ctx, updateRouteEnabled, arg.ID, arg.TenantID, arg.Enabled)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceID,
		&i.DestinationID,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}
