// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRule = `-- name: DeleteRule :execrows
DELETE FROM rules
WHERE id = $1 AND tenant_id = $2
`

type DeleteRuleParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteRule(ctx context.Context, arg DeleteRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRule, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRule = `-- name: GetRule :one
SELECT id, tenant_id, source_id, name, expression, action, route_destination_ids, priority, enabled, created_at, updated_at FROM rules
WHERE id = $1 AND tenant_id = $2
`

type GetRuleParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetRule(ctx context.Context, arg GetRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, getRule, arg.ID, arg.TenantID)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceID,
		&i.Name,
		&i.Expression,
		&i.Action,
		&i.RouteDestinationIds,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRule = `-- name: InsertRule :one
INSERT INTO rules (tenant_id, source_id, name, expression, action, route_destination_ids, priority, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, source_id, name, expression, action, route_destination_ids, priority, enabled, created_at, updated_at
`

type InsertRuleParams struct {
	TenantID            pgtype.UUID   `json:"tenant_id"`
	SourceID            pgtype.UUID   `json:"source_id"`
	Name                string        `json:"name"`
	Expression          string        `json:"expression"`
	Action              string        `json:"action"`
	RouteDestinationIds []pgtype.UUID `json:"route_destination_ids"`
	Priority            int32         `json:"priority"`
	Enabled             bool          `json:"enabled"`
}

func (q *Queries) InsertRule(ctx context.Context, arg InsertRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, insertRule,
		arg.TenantID,
		arg.SourceID,
		arg.Name,
		arg.Expression,
		arg.Action,
		arg.RouteDestinationIds,
		arg.Priority,
		arg.Enabled,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceID,
		&i.Name,
		&i.Expression,
		&i.Action,
		&i.RouteDestinationIds,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledRulesForSource = `-- name: ListEnabledRulesForSource :many
SELECT id, tenant_id, source_id, name, expression, action, route_destination_ids, priority, enabled, created_at, updated_at FROM rules
WHERE source_id = $1 AND enabled = true
ORDER BY priority, created_at
`

// Evaluation order: lower priority first, created_at as the tiebreaker so
// two rules at the same priority evaluate in creation order, deterministically.
func (q *Queries) ListEnabledRulesForSource(ctx context.Context, sourceID pgtype.UUID) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listEnabledRulesForSource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceID,
			&i.Name,
			&i.Expression,
			&i.Action,
			&i.RouteDestinationIds,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT id, tenant_id, source_id, name, expression, action, route_destination_ids, priority, enabled, created_at, updated_at FROM rules
WHERE tenant_id = $1
ORDER BY source_id, priority, created_at
`

func (q *Queries) ListRules(ctx context.Context, tenantID pgtype.UUID) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listRules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceID,
			&i.Name,
			&i.Expression,
			&i.Action,
			&i.RouteDestinationIds,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :one
UPDATE rules
SET name = $3, expression = $4, action = $5, route_destination_ids = $6,
    priority = $7, enabled = $8, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, source_id, name, expression, action, route_destination_ids, priority, enabled, created_at, updated_at
`

type UpdateRuleParams struct {
	ID                  pgtype.UUID   `json:"id"`
	TenantID            pgtype.UUID   `json:"tenant_id"`
	Name                string        `json:"name"`
	Expression          string        `json:"expression"`
	Action              string        `json:"action"`
	RouteDestinationIds []pgtype.UUID `json:"route_destination_ids"`
	Priority            int32         `json:"priority"`
	Enabled             bool          `json:"enabled"`
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, updateRule,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Expression,
		arg.Action,
		arg.RouteDestinationIds,
		arg.Priority,
		arg.Enabled,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceID,
		&i.Name,
		&i.Expression,
		&i.Action,
		&i.RouteDestinationIds,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
