// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSource = `-- name: GetSource :one
SELECT id, tenant_id, name, provider_type, endpoint_path, signing_secret_encrypted, signing_secret_key_version, verification_config, dedupe_enabled, dedupe_strategy, dedupe_field_path, dedupe_window_seconds, paused_at, created_at, updated_at FROM sources
WHERE id = $1 AND tenant_id = $2
`

type GetSourceParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// The test-event generator and other admin lookups fetch a source by
// id, scoped to the tenant like every other admin-authed query.
func (q *Queries) GetSource(ctx context.Context, arg GetSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, arg.ID, arg.TenantID)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ProviderType,
		&i.EndpointPath,
		&i.SigningSecretEncrypted,
		&i.SigningSecretKeyVersion,
		&i.VerificationConfig,
		&i.DedupeEnabled,
		&i.DedupeStrategy,
		&i.DedupeFieldPath,
		&i.DedupeWindowSeconds,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceByEndpointPath = `-- name: GetSourceByEndpointPath :one
SELECT id, tenant_id, name, provider_type, endpoint_path, signing_secret_encrypted, signing_secret_key_version, verification_config, dedupe_enabled, dedupe_strategy, dedupe_field_path, dedupe_window_seconds, paused_at, created_at, updated_at FROM sources
WHERE endpoint_path = $1
`

// Ingest looks a source up by its path segment to decide which
// verifier runs and which tenant/source the event belongs to.
func (q *Queries) GetSourceByEndpointPath(ctx context.Context, endpointPath string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByEndpointPath, endpointPath)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ProviderType,
		&i.EndpointPath,
		&i.SigningSecretEncrypted,
		&i.SigningSecretKeyVersion,
		&i.VerificationConfig,
		&i.DedupeEnabled,
		&i.DedupeStrategy,
		&i.DedupeFieldPath,
		&i.DedupeWindowSeconds,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceByName = `-- name: GetSourceByName :one
SELECT id, tenant_id, name, provider_type, endpoint_path, signing_secret_encrypted, signing_secret_key_version, verification_config, dedupe_enabled, dedupe_strategy, dedupe_field_path, dedupe_window_seconds, paused_at, created_at, updated_at FROM sources
WHERE tenant_id = $1 AND name = $2
ORDER BY created_at ASC
LIMIT 1
`

type GetSourceByNameParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
}

func (q *Queries) GetSourceByName(ctx context.Context, arg GetSourceByNameParams) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByName, arg.TenantID, arg.Name)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ProviderType,
		&i.EndpointPath,
		&i.SigningSecretEncrypted,
		&i.SigningSecretKeyVersion,
		&i.VerificationConfig,
		&i.DedupeEnabled,
		&i.DedupeStrategy,
		&i.DedupeFieldPath,
		&i.DedupeWindowSeconds,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSource = `-- name: InsertSource :one
INSERT INTO sources (
    tenant_id,
    name,
    provider_type,
    endpoint_path,
    signing_secret_encrypted,
    signing_secret_key_version,
    verification_config,
    dedupe_enabled,
    dedupe_strategy,
    dedupe_field_path,
    dedupe_window_seconds
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, tenant_id, name, provider_type, endpoint_path, signing_secret_encrypted, signing_secret_key_version, verification_config, dedupe_enabled, dedupe_strategy, dedupe_field_path, dedupe_window_seconds, paused_at, created_at, updated_at
`

type InsertSourceParams struct {
	TenantID                pgtype.UUID `json:"tenant_id"`
	Name                    string      `json:"name"`
	ProviderType            string      `json:"provider_type"`
	EndpointPath            string      `json:"endpoint_path"`
	SigningSecretEncrypted  []byte      `json:"signing_secret_encrypted"`
	SigningSecretKeyVersion pgtype.Int4 `json:"signing_secret_key_version"`
	VerificationConfig      []byte      `json:"verification_config"`
	DedupeEnabled           bool        `json:"dedupe_enabled"`
	DedupeStrategy          pgtype.Text `json:"dedupe_strategy"`
	DedupeFieldPath         pgtype.Text `json:"dedupe_field_path"`
	DedupeWindowSeconds     int32       `json:"dedupe_window_seconds"`
}

func (q *Queries) InsertSource(ctx context.Context, arg InsertSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, insertSource,
		arg.TenantID,
		arg.Name,
		arg.ProviderType,
		arg.EndpointPath,
		arg.SigningSecretEncrypted,
		arg.SigningSecretKeyVersion,
		arg.VerificationConfig,
		arg.DedupeEnabled,
		arg.DedupeStrategy,
		arg.DedupeFieldPath,
		arg.DedupeWindowSeconds,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ProviderType,
		&i.EndpointPath,
		&i.SigningSecretEncrypted,
		&i.SigningSecretKeyVersion,
		&i.VerificationConfig,
		&i.DedupeEnabled,
		&i.DedupeStrategy,
		&i.DedupeFieldPath,
		&i.DedupeWindowSeconds,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT id, tenant_id, name, provider_type, endpoint_path, signing_secret_encrypted, signing_secret_key_version, verification_config, dedupe_enabled, dedupe_strategy, dedupe_field_path, dedupe_window_seconds, paused_at, created_at, updated_at FROM sources
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSources(ctx context.Context, tenantID pgtype.UUID) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ProviderType,
			&i.EndpointPath,
			&i.SigningSecretEncrypted,
			&i.SigningSecretKeyVersion,
			&i.VerificationConfig,
			&i.DedupeEnabled,
			&i.DedupeStrategy,
			&i.DedupeFieldPath,
			&i.DedupeWindowSeconds,
			&i.PausedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
